---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: yarn install
      - name: Linting the project
        run: yarn lint
      - name: Building Docker image 
        uses: docker/build-push-action@v4
        with:
          context: ../..
          tags: dani450/webapp
          push: false
           
